//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPatterns.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignPatterns.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code not available.
        /// </summary>
        internal static string CODE_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("CODE_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string DEMO_BTN_TXT {
            get {
                return ResourceManager.GetString("DEMO_BTN_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [press a key to exit].
        /// </summary>
        internal static string DEMO_EXIT {
            get {
                return ResourceManager.GetString("DEMO_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [press a key to run code].
        /// </summary>
        internal static string DEMO_RUN_CODE {
            get {
                return ResourceManager.GetString("DEMO_RUN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [press a key to see code].
        /// </summary>
        internal static string DEMO_STANDARD_DESCRIPTION {
            get {
                return ResourceManager.GetString("DEMO_STANDARD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descr.
        /// </summary>
        internal static string DSCR_BTN_TXT {
            get {
                return ResourceManager.GetString("DSCR_BTN_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exmp.
        /// </summary>
        internal static string EXAMPLE_BTN_TXT {
            get {
                return ResourceManager.GetString("EXAMPLE_BTN_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the execution the following exception occur:
        ///{0}
        ///----
        ///{1}.
        /// </summary>
        internal static string EXCEPTION_MAIN_DISPLAY {
            get {
                return ResourceManager.GetString("EXCEPTION_MAIN_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No correct modes identified for the current application.
        /// </summary>
        internal static string EXCEPTION_MAIN_NOMODEAPP {
            get {
                return ResourceManager.GetString("EXCEPTION_MAIN_NOMODEAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Design pattern were found for ID {0} and Name &apos;{1}&apos;.
        /// </summary>
        internal static string EXCEPTION_MISSING_DESPATTERN {
            get {
                return ResourceManager.GetString("EXCEPTION_MISSING_DESPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Demo found for the design pattern of ID {0} and Name &apos;{1}&apos;.
        /// </summary>
        internal static string EXEPTION_DEMO_NOTFOUND {
            get {
                return ResourceManager.GetString("EXEPTION_DEMO_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string EXIT_BTN_TXT {
            get {
                return ResourceManager.GetString("EXIT_BTN_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File code not found.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MAIN_BTN_TXT {
            get {
                return ResourceManager.GetString("MAIN_BTN_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string MINIMIZE_BTN_TXT {
            get {
                return ResourceManager.GetString("MINIMIZE_BTN_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NEXT_BTN_TXT {
            get {
                return ResourceManager.GetString("NEXT_BTN_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code to display.
        /// </summary>
        internal static string NO_CODE_TO_DISPLAY {
            get {
                return ResourceManager.GetString("NO_CODE_TO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string PREV_BTN_TXT {
            get {
                return ResourceManager.GetString("PREV_BTN_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is still unavailable.
        /// </summary>
        internal static string UNAVAILABLE_CODE {
            get {
                return ResourceManager.GetString("UNAVAILABLE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        internal static string WRONG_EXAMPLE_BTN {
            get {
                return ResourceManager.GetString("WRONG_EXAMPLE_BTN", resourceCulture);
            }
        }
    }
}
